"""
Django settings for the Items API.

Generated by `django-admin startproject` (Django 6.0.7) and then edited in four places only:
INSTALLED_APPS, the secret/debug handling, the REST_FRAMEWORK block at the bottom, and — added
in Week 3, when browser apps started calling this API — CORS.

The rest is left exactly as Django ships it. A JSON API does not need the session, message or
static-file machinery, but trimming it is a decision about deployment rather than about this
exercise — and leaving it in place keeps an honest record of what `startproject` actually
gives you for a one-model API.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# A generated development key is fine for a local exercise, but it should never be the value
# that reaches a deployed environment — hence the override. Nothing secret is committed here.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-imp!u*_@sx8ka22&+$edb+nu*t0a*yhohgp^2rh457l2*96!+!',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() != 'false'

# 'testserver' is the host Django's own test client uses.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'items',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must run before CommonMiddleware. CommonMiddleware can answer a request with a redirect
    # before the CORS headers are ever attached, and a redirect without Access-Control-Allow-
    # Origin is an opaque failure in the browser's console — it reports a CORS error and says
    # nothing about the redirect that caused it.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# Timestamps are stored and returned as UTC, which is what the contract's `Z` suffix means.
USE_TZ = True


# Static files

STATIC_URL = 'static/'


# CORS
#
# Added in Week 3. The frontend apps are served from their own dev servers, so every request
# they make to this API is cross-origin, and a POST carrying application/json is preflighted.
#
# An explicit allowlist rather than CORS_ALLOW_ALL_ORIGINS: this API sends no credentials, so
# permitting every origin would buy nothing and hide a misconfigured port behind a request that
# happens to work.
#
# CSRF is not a problem here even though CsrfViewMiddleware is in the stack, because DRF's
# SessionAuthentication enforces CSRF only for requests that are actually session-authenticated
# — and these are anonymous. That is a property of this API having no authentication. The moment
# auth is added the question comes back and the answer changes.

CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',  # Angular dev server
    'http://localhost:5173',  # Vite dev server (Vue)
]

# django-cors-headers defaults to advertising DELETE, GET, OPTIONS, PATCH, POST and PUT. This
# contract has two verbs, and a preflight response promising four more that all answer 404 is
# misleading. Narrowed to match what the API actually serves — and to match the Nest side, so the
# two stacks do not differ here for a reason that has nothing to do with either framework.
CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS']


# Django REST Framework

REST_FRAMEWORK = {
    # Every error leaves through here as application/problem+json.
    'EXCEPTION_HANDLER': 'config.problem_details.problem_details_exception_handler',
    # DRF serialises DecimalField as a *string* by default, to protect precision through
    # JavaScript's float. The contract says `price` is a JSON number, so the coercion is
    # turned off deliberately rather than by accident.
    'COERCE_DECIMAL_TO_STRING': False,
}
